
# assignment-python
Problem statement :
https://docs.google.com/document/d/1dye0Qt6gB9YP8PMDyFQNle-Egw2JY39eJh66BmVYQtM

Execution: 

cd assignment

python search_buy_call.py

Notes:
1. In order to change any of the configuration there is conf.ini file in the assignment directory

2. The currently set account details for authentication have exhausted the available balance for buyingnew numbers hence no more new numbers can be bought, resulting in the test failure. 

3. Just by changing the auth_id and auth_token of an account which has balance in the conf.ini file will solve this and the test will run successfully. 
